[build]
builder = "nixpacks"

[build.nixpacks]
version = "1.38.0"

[deploy]
startCommand = "npm run start"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
NODE_VERSION = "22"
NPM_CONFIG_PRODUCTION = "false" 